cmake_minimum_required(VERSION 3.0.0 FATAL_ERROR)

project(${TCPPAP_BENCHMARK_NAME})

if (NOT TCPPAP_CXX_COMPILER_ID)
  set(TCPPAP_CXX_COMPILER_ID "${CMAKE_CXX_COMPILER_ID}")
endif()
  

if (UNIX)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_COMPILER_FLAGS} -std=c++14")
endif()


set(OLD_STYLE_EXE ${PROJECT_NAME}-old-style-${TCPPAP_CXX_COMPILER_ID})
set(MODERNCPP_STYLE_EXE ${PROJECT_NAME}-moderncpp-${TCPPAP_CXX_COMPILER_ID})

add_executable(${MODERNCPP_STYLE_EXE} ${TCPPAP_MODERNCPP_STYLE_SOURCES})

target_include_directories(
  ${MODERNCPP_STYLE_EXE}
  PRIVATE
  ${TCPPAP_INCLUDES}
  ${TCPPAP_MODERNCPP_STYLE_INCLUDES})

add_executable(${OLD_STYLE_EXE} ${TCPPAP_OLD_STYLE_SOURCES})

target_include_directories(
  ${OLD_STYLE_EXE}
  PRIVATE
  ${TCPPAP_INCLUDES}
  ${TCPPAP_OLD_STYLE_INCLUDES})


add_custom_command(TARGET ${MODERNCPP_STYLE_EXE}
   POST_BUILD
   COMMAND cmake -E remove -f ${MODERNCPP_STYLE_EXE}.dat
   COMMAND ${MODERNCPP_STYLE_EXE} ${TCPPAP_PROGRAM_ARGS} >> ${CMAKE_BINARY_DIR}/${MODERNCPP_STYLE_EXE}.dat
   COMMENT "Executing ${MODERNCPP_STYLE_EXE} ${TCPPAP_PROGRAM_ARGS}"
   VERBATIM)

add_custom_command(TARGET ${OLD_STYLE_EXE}
  POST_BUILD
  COMMAND cmake -E remove -f ${OLD_STYLE_EXE}.dat
  COMMAND ${OLD_STYLE_EXE} ${TCPPAP_PROGRAM_ARGS} >> ${CMAKE_BINARY_DIR}/${OLD_STYLE_EXE}.dat
  COMMENT "Executing ${OLD_STYLE_EXE} ${TCPPAP_PROGRAM_ARGS}")
